name: "Create PR to bump Homebrew formula"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-formula-pr:
    name: Create Formula Update PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This token is important for the PR creation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Tag version: ${VERSION}"

      - name: Update formula
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          
          # Update formula
          sed -i -E "s/tag:[[:space:]]+\"[^\"]+\"/tag:      \"${VERSION}\"/" Formula/tada.rb
          
          # Verify the change
          if grep -q "tag:.*\"${VERSION}\"" Formula/tada.rb; then
            echo "✅ Successfully updated formula to version ${VERSION}"
            git diff --color
          else
            echo "❌ Failed to update formula"
            exit 1
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(formula): bump tada to ${{ steps.version.outputs.VERSION }}"
          title: "chore(formula): bump tada to ${{ steps.version.outputs.VERSION }}"
          body: |
            ## 🚀 Formula Update
            
            This PR updates the Homebrew formula for tada to version `${{ steps.version.outputs.VERSION }}`.
            
            ### Changes
            - Updated `tag` in Formula/tada.rb to `${{ steps.version.outputs.VERSION }}`
            
            ---
            *This PR was automatically created by the release workflow.*
          branch: "bump-formula-${{ steps.version.outputs.VERSION }}"
          base: main
          delete-branch: true
          labels: |
            formula
            automated
