name: "Create PR to bump Homebrew formula"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-formula-pr:
    name: Create Formula Update PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: version
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create branch and update formula
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          BRANCH_NAME="bump-formula-${VERSION}"
          
          # Create new branch
          git checkout -b "${BRANCH_NAME}"
          
          # Update formula
          sed -i -E "s/tag:[[:space:]]+\"[^\"]+\"/tag:      \"${VERSION}\"/" Formula/tada.rb
          
          # Commit changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/tada.rb
          git commit -m "chore(formula): bump tada to ${VERSION}"
          
          # Push branch
          git push origin "${BRANCH_NAME}"
          
          # Set output for PR creation
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.create-branch.outputs.BRANCH_NAME }}
          title: "chore(formula): bump tada to ${{ steps.version.outputs.VERSION }}"
          body: |
            ## 🚀 Formula Update
            
            This PR updates the Homebrew formula for tada to version `${{ steps.version.outputs.VERSION }}`.
            
            ### Changes
            - Updated `tag` in Formula/tada.rb to `${{ steps.version.outputs.VERSION }}`
            
            ---
            *This PR was automatically created by the release workflow.*
          labels: |
            formula
            automated
